apiVersion: core.oam.dev/v1beta1
kind: DefinitionModule
metadata:
  name: kubevela-community-playground
spec:
  description: Runnable examples for merged KubeVela DefKit authoring capabilities
  maintainers:
    - name: Naveen Kumar Sangi
    - name: Krishnan K M
  categories:
    - examples
    - defkit
